### ISSUE TITLE
Database not finding for Our-E-School-Web-Portal

### ISSUE THREAD

**Issue by sunilmaniparaecs** [ketanchoyal/Our-E-School-Web-Portal#6]
Hello Ketan Choyal,
I have setup Our-E-School-Web-Portal [https://github.com/ketanchoyal/Our-E-School-Web-Portal]  but i can't see **database** for it. so can you please help me, how to set **database**?

Thank you!

**Comment by ketanchoyal** [comment]
Web portal is still under development, I haven't added database part yet

**Comment by MadhavShah** [comment]
Hello Ketan Choyal,
How much time are you expecting for Web-Portal to finish?

**Comment by ketanchoyal** [comment]
@MadhavShah  It is going to take time as I’m not currently working on it.

You can work on it if want and the do the PR.
